export const AvenuesParams = {
    COMMAND: "command",
    ACCESS_CODE: "access_code",
    MERCHANT_ID: "merchant_id",
    ORDER_ID: "order_id",
    AMOUNT: "amount",
    CURRENCY: "currency",
    REDIRECT_URL: "redirect_url",
    CANCEL_URL: "cancel_url",
    LANGUAGE: "language",
    BILLING_NAME: "billing_name",
    BILLING_ADDRESS: "billing_address",
    BILLING_CITY: "billing_city",
    BILLING_STATE: "billing_state",
    BILLING_ZIP: "billing_zip",
    BILLING_COUNTRY: "billing_country",
    BILLING_TEL: "billing_tel",
    BILLING_EMAIL: "billing_email",
    DELIVERY_NAME: "delivery_name",
    DELIVERY_ADDRESS: "delivery_address",
    DELIVERY_CITY: "delivery_city",
    DELIVERY_STATE: "delivery_state",
    DELIVERY_ZIP: "delivery_zip",
    DELIVERY_COUNTRY: "delivery_country",
    DELIVERY_TEL: "delivery_tel",
    MERCHANT_PARAM1: "merchant_param1",
    MERCHANT_PARAM2: "merchant_param2",
    MERCHANT_PARAM3: "merchant_param3",
    MERCHANT_PARAM4: "merchant_param4",
    MERCHANT_PARAM5: "merchant_param5",
    PAYMENT_OPTION: "payment_option",
    CARD_TYPE: "card_type",
    CARD_NAME: "card_name",
    DATA_ACCEPTED_AT: "data_accept",
    CARD_NUMBER: "card_number",
    EXPIRY_MONTH: "expiry_month",
    EXPIRY_YEAR: "expiry_year",
    CVV: "cvv_number",
    ISSUING_BANK: "issuing_bank",
    ENC_VAL: "enc_val",
    RSA_KEY_URL: "rsa_key_url",
    CUSTOMER_IDENTIFIER: "customer_identifier",
    SAVE_CARD: "saveCard",
    EMI_PLAN_ID: "emi_plan_id",
    EMI_TENURE_ID: "emi_tenure_id",
    RESP_TYPE: "response_type",
    PROMO_CODE: "promo_code",

    SI_TYPE: "si_type",
    SI_REF_NO: "si_mer_ref_no",
    SI_SETUP_AMT: "si_is_setup_amt",
    SI_AMT: "si_amount",
    SI_START_DATE: "si_start_date",
    SI_FREQ_TYPE: "si_frequency_type",
    SI_FREQ: "si_frequency",
    SI_BILL_CYCLE: "si_bill_cycle",
}

export const Constants = {
	 PARAMETER_SEP : "&",
	 PARAMETER_EQUALS : "=",
	//  JSON_URL : "https://secure.ccavenue.ae/transaction/transaction.do",
	 TRANS_URL : "https://secure.ccavenue.com/transaction/initTrans",
	//  SETTING_URL : "https://secure.ccavenue.ae/transaction/appapi.do?command=getMerchantSetting",

	 VAULT : "",
	 BILLING : "",
	 SHIPPING : "",
	 PROMOTION : "",
	 DISCOUNT : "",
}

export const MerchantParams = {
    
      access_code: '4YRUXLSRO20O8NIH',
      merchant_id: '2',
      currency:'INR',
      redirect_url: 'http://bhulekhapp.in/live/ccav_resp.php',
      cancel_url: 'http://bhulekhapp.in/live/ccav_resp.php',
      rsa_key_url: 'http://bhulekhapp.in/live/GetRSA.php'
    
      
}